apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-service
  labels:
    app: distributed-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distributed-service
  template:
    metadata:
      labels:
        app: distributed-service
    spec:
      containers:
      - name: app
        image: distributed-service:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: GIN_MODE
          value: release
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
