server:
  port: 8080
  mode: debug
  name: distributed-service
  version: v1.0.0
  tags: "myapp,test-server"

logger:
  level: debug
  encoding: console
  output_path: stdout

jwt:
  secret_key: "your-super-secret-jwt-key-change-in-production"
  issuer: "distributed-service"

consul:
  host: localhost
  port: 8500
  service_check_interval: 10s
  deregister_critical_service_after: 30s

metrics:
  enabled: true
  prometheus_port: 9090

mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: distributed_service
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  vhost: /

tracing:
  service_name: distributed-service
  service_version: v1.0.0
  environment: development
  enabled: true
  exporter_type: stdout  # 可选: "otlp", "stdout"
  endpoint: "localhost:14268"  # Jaeger endpoint
  sample_ratio: 1.0  # 1.0 表示采样所有请求，生产环境建议设为 0.1 或更小 