server:
  port: 8080
  mode: release
  name: distributed-service
  version: v1.0.0
  tags: "myapp,test-server"

logger:
  level: info
  encoding: json
  output_path: stdout

jwt:
  secret_key: "your-super-secret-jwt-key-change-in-production"
  issuer: "distributed-service"

consul:
  host: consul
  port: 8500
  service_check_interval: 10s
  deregister_critical_service_after: 30s

metrics:
  enabled: true
  prometheus_port: 9090

mysql:
  host: mysql
  port: 3306
  username: root
  password: root
  database: distributed_service
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: redis
  port: 6379
  password: ""
  db: 0
  pool_size: 100

rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
  vhost: /

tracing:
  service_name: distributed-service
  service_version: v1.0.0
  environment: production
  enabled: true
  exporter_type: otlp
  endpoint: "jaeger:4318"
  sample_ratio: 0.1 