server:
  port: 8080
  mode: release
  name: distributed-service
  version: v1.0.0
  tags: "myapp,test-server"

logger:
  level: info
  encoding: json
  output_path: stdout

jwt:
  secret_key: "your-super-secret-jwt-key-change-in-production"
  issuer: "distributed-service"

consul:
  host: consul
  port: 8500
  service_check_interval: 10s
  deregister_critical_service_after: 30s

metrics:
  enabled: true
  prometheus_port: 9090

mysql:
  host: mysql
  port: 3306
  username: root
  password: root
  database: distributed_service
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: redis
  port: 6379
  password: ""
  db: 0
  pool_size: 100

rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
  vhost: /

tracing:
  service_name: distributed-service
  service_version: v1.0.0
  environment: production
  enabled: true
  exporter_type: otlp
  endpoint: "jaeger:4318"
  sample_ratio: 0.1

ratelimit:
  enabled: true
  store_type: redis  # 支持 memory, redis
  redis_prefix: "ratelimit:"
  default_config:
    health_check: "10-S"      # 健康检查：每秒10次
    auth_public: "20-M"       # 认证公开端点：每分钟20次
    auth_protected: "10-M"    # 认证保护端点：每分钟10次
    user_public: "30-M"       # 用户公开API：每分钟30次
    user_protected: "50-M"    # 用户保护API：每分钟50次
  endpoints:
    "/health": "10-S"
    "/api/v1/auth/register": "20-M"
    "/api/v1/auth/login": "20-M"
    "/api/v1/auth/refresh": "20-M"
    "/api/v1/auth/change-password": "10-M"
    "/api/v1/users/me": "50-M"
    "/api/v1/users": "30-M" 